"""empty message

Revision ID: 133fb6418e26
Revises: None
Create Date: 2016-10-03 21:23:29.347029

"""

# revision identifiers, used by Alembic.
revision = '133fb6418e26'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startTime', sa.Text(), nullable=True),
    sa.Column('endTime', sa.Text(), nullable=True),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passengersList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('carId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rideList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventId', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('driver', sa.Text(), nullable=True),
    sa.Column('departureTime', sa.Text(), nullable=True),
    sa.Column('returnTime', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rideList')
    op.drop_table('passengersList')
    op.drop_table('eventList')
    ### end Alembic commands ###
