"""empty message

Revision ID: 2e3402f5e486
Revises: 133fb6418e26
Create Date: 2016-10-03 23:04:55.861848

"""

# revision identifiers, used by Alembic.
revision = '2e3402f5e486'
down_revision = '133fb6418e26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventList', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('eventList', 'endTime',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('eventList', 'host',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('eventList', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('eventList', 'startTime',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('passengersList', 'carId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('passengersList', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'passengersList', 'rideList', ['carId'], ['id'])
    op.alter_column('rideList', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rideList', 'comments',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('rideList', 'departureTime',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('rideList', 'driver',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('rideList', 'eventId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rideList', 'returnTime',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'rideList', 'eventList', ['eventId'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rideList', type_='foreignkey')
    op.alter_column('rideList', 'returnTime',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('rideList', 'eventId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rideList', 'driver',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('rideList', 'departureTime',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('rideList', 'comments',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('rideList', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'passengersList', type_='foreignkey')
    op.alter_column('passengersList', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('passengersList', 'carId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('eventList', 'startTime',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('eventList', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('eventList', 'host',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('eventList', 'endTime',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('eventList', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###
